disabled_rules:
 - trailing_whitespace
 - unused_closure_parameter
excluded: # 執行 linting 時忽略的路徑。 優先順序比 included 更高。
 - Pods
 - Carthage
identifier_name:
min_length: # only min_length
  error: 4 # only error
excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey